language: r
r:
  - devel
# dependency detection in R Travis is buggy, it fails to install gmp
# and we also want covr
r_packages:
  - gmp
  - covr
cache: packages
matrix:
  include:
  - os: linux
    dist: bionic
    after_success: Rscript -e 'covr::codecov(type="all")'
  - os: osx
    latex: false
    #disable_homebrew: true
